use_default_settings: true

general:
  instance_name: "MarketCouncil Search"

search:
  safe_search: 1
  formats:
    - html
    - json

server:
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
  secret_key: "marketcouncil-local-only"
