import React,{useState,useEffect} from 'react';
import {supabase} from './account.js';
import {measurementReport,metricText,monitoringSummary} from './adminData.js';
export function useAdmin(session){
 const [allowed,setAllowed]=useState(false),[checking,setChecking]=useState(true);
 useEffect(()=>{let active=true;setAllowed(false);setChecking(true);if(!supabase||!session){setChecking(false);return;}
 supabase.rpc('is_official_editor').then(({data,error})=>{if(active){setAllowed(!error&&data===true);setChecking(false)}}).catch(()=>{if(active)setChecking(false)});return()=>{active=false};},[session?.user.id]);
 return {allowed,checking};
}
export default function Admin({session,allowed,checking}){
 const [tab,setTab]=useState('monitoring'),[rows,setRows]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;setRows([]);if(!allowed||!session||!supabase)return;setLoading(true);setError('');
 supabase.from('admin_reports').select('id,kind,recorded_at,label,payload').order('recorded_at',{ascending:false}).limit(200).then(({data,error})=>{if(active){if(error)setError('측정 기록 저장소 연결을 확인하세요.');else {const valid=[];for(const row of data||[]){try{const payload=measurementReport(row.payload);if(payload.id!==row.id||payload.kind!==row.kind)throw Error();valid.push({...row,payload});}catch{setError('형식이 잘못된 기록은 표시하지 않았습니다.');}}setRows(valid);}setLoading(false)}}).catch(()=>{if(active){setError('기록을 불러오지 못했습니다.');setLoading(false)}});return()=>{active=false};},[allowed,session?.user.id]);
 async function upload(event){const file=event.target.files?.[0];if(!file)return;setBusy(true);setError('');setNotice('');
 try{if(file.size>1024*1024)throw Error('1MB 이하의 성능 기록을 선택하세요.');const payload=measurementReport(JSON.parse(await file.text()));const row={id:payload.id,user_id:session.user.id,kind:payload.kind,recorded_at:payload.recorded_at,label:payload.label,payload};const {error}=await supabase.from('admin_reports').insert(row);if(error)throw Error(error.code==='23505'?'이미 저장된 측정 기록입니다.':'기록을 저장하지 못했습니다. 관리자 권한을 확인하세요.');setRows(prev=>[row,...prev].sort((a,b)=>b.recorded_at.localeCompare(a.recorded_at)).slice(0,200));setTab(payload.kind);setNotice('관리자 전용 기록으로 보관했습니다.');}
 catch(e){setError(e instanceof SyntaxError?'JSON 파일 형식을 확인하세요.':e.message)}finally{setBusy(false);event.target.value=''}}
 if(checking)return <section className="account-page"><p role="status">관리자 권한을 확인하고 있습니다.</p></section>;
 if(!allowed)return <section className="account-page"><h1>관리자 페이지</h1><p role="alert">공식 운영자 계정으로 로그인해야 접근할 수 있습니다.</p></section>;
 const reports=rows.filter(x=>x.kind===tab).map(x=>x.payload),summary=monitoringSummary(reports),latest=reports[0],web=reports.find(r=>r.scope==='web_lighthouse');
 return <section className="account-page admin-page"><span className="eyebrow">ADMIN · MEASURED DATA</span><h1>서비스 성능과 근거 품질</h1><p>실제 측정 기록을 비교합니다. 과거 실행 시간과 AI 정확도를 추정하지 않습니다.</p><nav className="tabs" aria-label="관리자 성능 페이지"><button aria-pressed={tab==='monitoring'} onClick={()=>setTab('monitoring')}>운영 모니터링</button><button aria-pressed={tab==='rag'} onClick={()=>setTab('rag')}>RAG 벤치마크</button></nav><label className="result-import">성능 기록 가져오기<input type="file" accept=".json,application/json" disabled={busy} onChange={upload}/></label>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{loading&&<p role="status">측정 기록을 불러오는 중입니다.</p>}
 {tab==='monitoring'?<><h2>운영 모니터링</h2><div className="detail-metrics"><div><span>분석 실행 표본</span><strong>{summary.count}</strong></div><div><span>분석 성공률</span><strong>{metricText(summary.successRate,true)}</strong></div><div><span>평균 분석 시간 · 초</span><strong>{metricText(summary.averageMs===null?null:summary.averageMs/1000)}</strong></div><div><span>토큰·API 비용</span><strong className="word">미측정</strong></div></div><p className="muted">PC에서 측정해 업로드한 실행만 집계합니다. 미업로드 실행과 PC가 꺼진 시간은 관측하지 않습니다. 서비스 전체 가용성을 뜻하지 않습니다.</p></>:<><h2>RAG 검색 품질</h2><div className="detail-metrics">{[['정답 근거 포함률','recall'],['검색 정밀도','precision'],['정답의 검색 순위 · MRR','mrr'],['검색 지연 p95 · ms','p95_ms']].map(([label,key])=><div key={key}><span>{label}</span><strong>{metricText(latest?.metrics[key],key!=='p95_ms')}</strong></div>)}</div><p className="muted">최신 평가 기록 기준입니다. 정답 근거가 지정된 고정 질문으로 측정하며 모델 준비 시간은 제외합니다. 데이터셋·문서 저장소·모델·검색 개수가 같은 기록끼리 비교하세요. AI 답변 정확도와 인용 평가는 별도입니다.</p></>}
 {!loading&&reports.length===0&&<div className="paper"><h3>아직 측정 기록이 없습니다.</h3><p>{tab==='rag'?'실제 문서에서 질문과 정답 근거를 지정한 평가 데이터셋을 준비한 뒤, 로컬 평가 결과를 가져오세요. 임의 점수나 예시 결과는 표시하지 않습니다.':'다음 로컬 분석에서 생성되는 metrics 폴더의 기록을 가져오세요. 기존 배포 0.4.0에는 자동 시간 수집이 포함되지 않았습니다. 소스 실행부터 기록됩니다.'}</p></div>}
 {tab==='monitoring'&&web&&<><h2>웹 페이지 성능 · Lighthouse</h2><div className="detail-metrics">{[['성능 점수','performance_score'],['주요 콘텐츠 표시 · LCP ms','lcp_ms'],['화면 이동 · CLS','cls'],['작업 지연 · TBT ms','tbt_ms']].map(([label,key])=><div key={key}><span>{label}</span><strong>{metricText(web.metrics[key],key==='performance_score')}</strong></div>)}</div><p className="muted">{new Date(web.recorded_at).toLocaleString('ko-KR')} · {web.settings.form_factor} 실험실 측정 1회 · Lighthouse {web.settings.lighthouse_version}. 실제 방문자 평균이나 서비스 가용성 지표가 아닙니다.</p></>}{reports.length>0&&<><h2>{tab==='rag'?'평가 설정과 버전별 비교':'최근 측정 기록'}</h2><div className="admin-table"><table><thead><tr><th>측정 시각</th><th>대상·버전</th>{tab==='rag'?<><th>평가 조건</th><th>Recall / MRR</th><th>p95 ms</th><th>기업 혼입 / 미래 자료</th></>:<><th>측정 범위</th><th>처리 시간 · 초</th><th>상태</th></>}</tr></thead><tbody>{reports.map(r=><tr key={r.id}><td>{new Date(r.recorded_at).toLocaleString('ko-KR')}</td><td>{r.label}<br/><small>{r.version}</small></td>{tab==='rag'?<><td>{r.settings.case_count}문항 · k={r.settings.top_k} · {r.settings.repeats}회<br/><small>모델 {r.settings.model||'미지정'}<br/>데이터셋 {r.dataset_hash?.slice(0,12)}<br/>저장소 {r.settings.corpus_hash?.slice(0,12)||'미지정'}</small></td><td>{metricText(r.metrics.recall,true)} / {metricText(r.metrics.mrr,true)}</td><td>{metricText(r.metrics.p95_ms)}</td><td>{metricText(r.metrics.mixed_company)} / {metricText(r.metrics.future_sources)}<br/><small>기업 미상 {metricText(r.metrics.unknown_company)}</small></td></>:<><td>{r.scope}<br/><small>{r.environment.os||'환경 미지정'} · {r.environment.cpu_count||'—'} CPU</small></td><td>{metricText(r.metrics.duration_ms/1000)}</td><td>{r.status==='success'?'성공':'실패'}</td></>}</tr>)}</tbody></table></div><h2>처리 시간 추이</h2><div className="admin-bars" role="img" aria-label="최근 기록의 처리 시간 비교">{reports.slice(0,12).reverse().map(r=>{const value=tab==='rag'?r.metrics.median_ms:r.metrics.duration_ms,max=Math.max(...reports.slice(0,12).map(x=>tab==='rag'?x.metrics.median_ms:x.metrics.duration_ms),1);return <div key={r.id}><span>{new Date(r.recorded_at).toLocaleDateString('ko-KR')}</span><div><i style={{width:(value/max*100)+'%'}}/></div><span>{metricText(value)} ms</span></div>})}</div><p className="muted">최근 200건을 표시합니다. 그래프는 서로 다른 측정 범위를 포함할 수 있으므로 같은 조건의 수치를 비교하세요.</p></>}
 </section>;
}
